# group_vars/all.yml
# Variables visible to all nodes
---
# Allow vagrant user and Jenkins to run Docker commands
docker_users:
  - vagrant

# Install Docker Compose
docker_install_compose_plugin: true
docker_install_compose: false
