# site.yml
---
- name: Setup Jenkins
  hosts: all
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.docker

  tasks:
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present
